### ISSUE TITLE
Debug project

### ISSUE THREAD

**Issue by egarmar1** [mmonfared/CyFramework#3]
How do i debug the project choosing a breakpoint, thanks

**Comment by mmonfared** [comment]
Hi, you can use `debugger` or ``cy.debug()` anywhere you want, open devtools in cypress and then run the test. It will pause at the breakpoint. 
This is Cypress documentation about it > https://docs.cypress.io/api/commands/debug
Here I have some examples > https://github.com/mmonfared/automationcamp-cypress/blob/master/cypress/e2e/Session23_Debug_Log.cy.js
